Web/WonderlandBooks.Web/Controllers/AuthorsController.cs
namespace WonderlandBooks.Web.Controllers
{
    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;

    using WonderlandBooks.Services.Data.ControllerDataService;
    using WonderlandBooks.Web.ViewModels.Authors;

    public class AuthorsController : BaseController
    {
        private readonly IAuthorsService authorsService;
        private readonly IMapper mapper;

        public AuthorsController(
            IAuthorsService authorsService,
            IMapper mapper)
        {
            this.authorsService = authorsService;
            this.mapper = mapper;
        }

        public IActionResult Author(int id)
        {
            var model = this.mapper.Map<AuthorViewModel>(this.authorsService.Author<AuthorViewModel>(id));
            return this.View(model);
        }

        public IActionResult AllAuthors(int id = 1)
        {
            const int ItemPerPage = 8;
            var model = new AuthorsPagingViewModel()
            {
                ItemPerPage = ItemPerPage,
                PageNumber = id,
                Count = this.authorsService.GetCount(),
                Authors = this.authorsService.GetAllBooks<AuthorsListViewModel>(id, ItemPerPage),
            };

            return this.View(model);
        }
    }
}

Web/WonderlandBooks.Web/Controllers/BooksController.cs
namespace WonderlandBooks.Web.Controllers
{
    using System.Threading.Tasks;

    using AutoMapper;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using WonderlandBooks.Data.Models;
    using WonderlandBooks.Services.Data.ControllerDataService;
    using WonderlandBooks.Services.Data.InputDataServices;
    using WonderlandBooks.Web.ViewModels.Books;

    public class BooksController : BaseController
    {
        private readonly IMapper mapper;
        private readonly IBooksService booksService;
        private readonly UserManager<ApplicationUser> userManager;

        public BooksController(
            IMapper mapper,
            IBooksService booksService,
            UserManager<ApplicationUser> userManager)
        {
            this.mapper = mapper;
            this.booksService = booksService;
            this.userManager = userManager;
        }

        public IActionResult Book(int id)
        {
            const int RANDOM_BOOKS_COUNT = 12;

            var model = new RandomListBookViewModel
            {
                Book = this.mapper.Map<BookViewModel>(this.booksService.GetBook<BookViewModel>(id)),
                RandomBooks = this.booksService.GetRandom<BooksListViewModel>(RANDOM_BOOKS_COUNT),
            };

            return this.View(model);
        }

        public async Task<IActionResult> Library()
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var model = this.mapper.Map<ListOfBooksLibraryViewModel>(this.booksService.GetLibrary<ListOfBooksLibraryViewModel>(user.Id));

            return this.View(model);
        }

        public IActionResult AllBooks(int id = 1)
        {
            const int ItemPerPage = 16;
            var model = new BooksPagingViewModel()
            {
                ItemPerPage = ItemPerPage,
                PageNumber = id,
                Count = this.booksService.GetCount(),
                Books = this.booksService.GetAllBooks<BooksListViewModel>(id, ItemPerPage),
            }; 
            return this.View(model);
        }

        public IActionResult SearchBook(string search, int id = 1)
        {
            int itemPerPage = 10;
            var model = new SearchListBookViewModel
            {
                ItemPerPage = itemPerPage,
                PageNumber = id,
                SearchString = search,
                Count = this.booksService.GetCountBySearch(search),
                Books = this.booksService.GetBooksByName<SearchBooksViewModel>(search, id, itemPerPage),
            };

            return this.View(model);
        }
    }
}

Web/WonderlandBooks.Web/Controllers/CreativeWritingController.cs
namespace WonderlandBooks.Web.Controllers
{
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using AutoMapper;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using WonderlandBooks.Data.Models;
    using WonderlandBooks.Services.Data.ControllerDataService;
    using WonderlandBooks.Services.Data.InputDataServices;
    using WonderlandBooks.Web.ViewModels.CreativeWriting;
    using WonderlandBooks.Web.ViewModels.CreativeWriting.InputModelSelectList;

    public class CreativeWritingController : BaseController
    {
        private readonly IGenreInputModelListItems genreInputModel;
        private readonly IEditionLanguageInputModelListItems editionLanguageInputModel;
        private readonly IMapper mapper;
        private readonly IModifiedStoryService storyService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment hostEnvironment;
        private readonly IStoriesService storiesService;
        private readonly IModifiedChapterService modifiedChapterService;
        private readonly IChapterService chapterService;

        public CreativeWritingController(
            IGenreInputModelListItems genreInputModel,
            IEditionLanguageInputModelListItems editionLanguageInputModel,
            IMapper mapper,
            IModifiedStoryService modifiedStoryService,
            UserManager<ApplicationUser> userManager,
            IWebHostEnvironment hostEnvironment,
            IStoriesService storiesService,
            IModifiedChapterService modifiedChapterService,
            IChapterService chapterService)
        {
            this.genreInputModel = genreInputModel;
            this.editionLanguageInputModel = editionLanguageInputModel;
            this.mapper = mapper;
            this.storyService = modifiedStoryService;
            this.userManager = userManager;
            this.hostEnvironment = hostEnvironment;
            this.storiesService = storiesService;
            this.modifiedChapterService = modifiedChapterService;
            this.chapterService = chapterService;
        }

        public IActionResult AllStories(int id = 1)
        {
            const int ItemPerPage = 8;


            var model = new AllStoriesViewModel
            {
                ItemPerPage = ItemPerPage,
                PageNumber = id,
                Count = this.storiesService.GetAllCount(),
                Stories = this.storiesService.AllStories<StoriesViewModel>(id, ItemPerPage),
            };

            return this.View(model);
        }

        public IActionResult CurrentStory(int id)
        {
            var model = this.mapper.Map<StoryViewModel>(this.storiesService.CurrentStory<StoryViewModel>(id));
            return this.View(model);
        }

        [Authorize]
        public async Task<IActionResult> StoriesByUser(int id = 1)
        {
            const int itemPerPage = 8;
            var user = await this.userManager.GetUserAsync(this.User);

            var model = this.mapper.Map<CollectionOfStories>(this.storiesService.UserWritring<CollectionOfStories>(user.Id));

            model.ItemPerPage = itemPerPage;
            model.PageNumber = id;
            model.Count = this.storiesService.GetCountByUser(user.Id);
            model.StoriesStorage = this.storiesService.StoriesByUser<StoriesViewModel>(user.Id, id, itemPerPage);

            return this.View(model);
        }

        [Authorize]
        public IActionResult CreateStory()
        {
            this.ViewBag.Genres = new SelectList(this.genreInputModel.Options, "Value", "Text");
            this.ViewBag.Language = new SelectList(this.editionLanguageInputModel.Options, "Value", "Text");

            return this.View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CreateStory(CreateStoryInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                this.ViewBag.Genres = new SelectList(this.genreInputModel.Options, "Value", "Text");
                this.ViewBag.Language = new SelectList(this.editionLanguageInputModel.Options, "Value", "Text");
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            input.UserId = user.Id;

            var path = this.hostEnvironment.WebRootPath;
            await this.storyService.CreateAsync(input, path);

            return this.Redirect("StoriesByUser");
        }

        [Authorize]
        public IActionResult UpdateStory(int idStory)
        {
            this.ViewBag.Genres = new SelectList(this.genreInputModel.Options, "Value", "Text");
            this.ViewBag.Language = new SelectList(this.editionLanguageInputModel.Options, "Value", "Text");

            var model = this.mapper.Map<UpdateStoryViewModel>(this.storiesService.CurrentStory<UpdateStoryViewModel>(idStory));

            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> UpdateStory(UpdateStoryViewModel input, string imagePath)
        {
            if (!this.ModelState.IsValid)
            {
                this.ViewBag.Genres = new SelectList(this.genreInputModel.Options, "Value", "Text");
                this.ViewBag.Language = new SelectList(this.editionLanguageInputModel.Options, "Value", "Text");
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            input.UserId = user.Id;

            var path = this.hostEnvironment.WebRootPath;
            await this.storyService.UpdateAsync(input, imagePath, path);

            return this.RedirectToAction("StoriesByUser");
        }

        [Authorize]
        public IActionResult CreateChapter(int idStory)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(idStory);
            }

            CreateChapterInputModel model = new CreateChapterInputModel
            {
                StoryId = idStory,
            };
            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> CreateChapter(CreateChapterInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction("AddChapter");
            }

            await this.modifiedChapterService.CreateAsync(input);

            return this.RedirectToAction("StoriesByUser");
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> UpdateChapter(UpdateChapterViewModel input, int id)
        {
            await this.modifiedChapterService.UpdateAsync(input);
            return this.RedirectToAction("StoriesByUser");
        }

        [Authorize]
        [Route("SelectChapter/{id:int}")]
        public IActionResult SelectChapter(int id)
        {
            var model = this.chapterService.CurrentChapter<UpdateChapterViewModel>(id);
            return this.View(model);
        }

        [Authorize]
        public IActionResult GetChapters(int idStory)
        {
            var model = this.mapper.Map<CollectionOfChapters>(this.storiesService.CurrentStory<CollectionOfChapters>(idStory));
            return this.View(model);
        }

        public IActionResult AddChapter(int idStory)
        {
            CreateChapterInputModel model = new CreateChapterInputModel
            {
                StoryId = idStory,
            };
            return this.View(model);
        }
    }
}

Web/WonderlandBooks.Web/Views/Shared/_Favicons.cshtml
<link rel="apple-touch-icon" sizes="180x180" href="~/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="~/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="~/favicon/favicon-16x16.png">
<link rel="manifest" href="~/favicon/site.webmanifest">
<link rel="mask-icon" href="~/favicon/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

Web/WonderlandBooks.Web/Views/Shared/_Layout.cshtml
@using WonderlandBooks.Common

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link href="assets/img/favicon.ico" rel="icon" type="image/png">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/animate.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/flaticon.css">
    <link rel="stylesheet" href="~/css/style.css">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="~/vendor/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/lazy.css">
    <link rel="stylesheet" href="~/css/demo.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
    @await this.RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-primary ftco-navbar-light" id="ftco-navbar">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName.</a>
                <form action="#" class="searchform order-sm-start order-lg-last">
                    <div class="form-group d-flex">
                        <form method="get">
                            <div class="input-group">
                                <input type="search" name="search" class="form-control rounded" placeholder="Search books" aria-label="Search" aria-describedby="search-addon" />
                                <button type="submit" class="btn btn-outline-primary" asp-controller="Books" asp-action="SearchBook">search</button>
                            </div>
                        </form>
                    </div>
                </form>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="fa fa-bars"></span> Menu
                </button>
                <div class="collapse navbar-collapse" id="ftco-nav">
                    <ul class="navbar-nav m-auto">
                        <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Books" asp-action="AllBooks">Books</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Authors" asp-action="AllAuthors">Authors</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="CreativeWriting" asp-action="AllStories">Stories</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Profil</a>
                            <div class="dropdown-menu" aria-labelledby="dropdown04">
                                <partial name="_LoginPartial" />
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <partial name="_CookieConsentPartial" />
    <main role="main" class="pb-3">
        @this.RenderBody()
    </main>

    <!--foother -->

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js"></script>

    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/popper/popper.min.js"></script>
    <script src="~/vendor/bootstrap/bootstrap.min.js"></script>

    <script src="~/vendor/nouislider/js/nouislider.min.js"></script>
    <script src="~/js/lazy.js"></script>

    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/jquery.stellar.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/jquery.animateNumber.min.js"></script>
    <script src="~/js/scrollax.min.js"></script>
    <script src="~/js/main.js"></script>
    <script src="https://kit.fontawesome.com/393aca35f7.js" crossorigin="anonymous"></script>
    @await this.RenderSectionAsync("Scripts", required: false)

</body>
</html>