Web/WonderlandBooks.Web/Controllers/GenresController.cs
namespace WonderlandBooks.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using WonderlandBooks.Services.Data.ControllerDataService;
    using WonderlandBooks.Web.ViewModels.Genres;

    public class GenresController : BaseController
    {
        private readonly IGenreSerivice genreSerivice;
        private readonly IPostService postService;

        public GenresController(
            IGenreSerivice genreSerivice,
            IPostService postService)
        {
            this.genreSerivice = genreSerivice;
            this.postService = postService;
        }

        public IActionResult GenreList()
        {
            var model = new GenreListViewModel
            {
                Genres = this.genreSerivice.TopGenres<GenreViewModel>(),
            };
            return this.View(model);
        }

        public IActionResult PostByName(int id, int page = 1)
        {
            int itemPerPage = 10;
            var model = this.genreSerivice.PostByName<GenrePostViewModel>(id);
            model.ItemPerPage = itemPerPage;
            model.PageNumber = page;
            model.Count = this.postService.GetCount(id);
            model.FormPost = this.postService.GetPostByGenre<PostViewModel>(id, page, itemPerPage);
            return this.View(model);
        }
    }
}

Web/WonderlandBooks.Web/Controllers/PostsController.cs
namespace WonderlandBooks.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using WonderlandBooks.Services.Data.ControllerDataService;
    using WonderlandBooks.Services.Data.InputDataServices;
    using WonderlandBooks.Web.ViewModels.CreativeWriting.InputModelSelectList;
    using WonderlandBooks.Web.ViewModels.Posts;

    public class PostsController : BaseController
    {
        private readonly IGenreInputModelListItems genreInputModel;
        private readonly IModifiedPostService editPostService;
        private readonly IPostService postService;

        public PostsController(
            IGenreInputModelListItems genreInputModel,
            IModifiedPostService editPostService,
            IPostService postService)
        {
            this.genreInputModel = genreInputModel;
            this.editPostService = editPostService;
            this.postService = postService;
        }

        [Authorize]
        public IActionResult ById(int id)
        {
            var model = this.postService.ById<PostViewModel>(id);
            return this.View(model);
        }

        [Authorize]
        public IActionResult Create()
        {
            this.ViewBag.Genres = new SelectList(this.genreInputModel.Options, "Value", "Text");

            return this.View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(PostCreateInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                this.ViewBag.Genres = new SelectList(this.genreInputModel.Options, "Value", "Text");
                return this.View(model);
            }

            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            await this.editPostService.CreateAsync(model, userId);

            return this.Redirect("/Genres/GenreList");
        }
    }
}

Web/WonderlandBooks.Web/Views/Genres/GenreList.cshtml
@model WonderlandBooks.Web.ViewModels.Genres.GenreListViewModel
@{
    this.ViewData["Title"] = "Topics";
}
<a class="btn btn-block" asp-controller="Posts" asp-action="Create"><h1>Create new post</h1> </a>
<div class="row">
    @foreach (var genre in Model.Genres)
    {
    
        <div class="card w-25 text-center">
            <div class="card-body">
                <h3 class="card-title">@genre.Name</h3>
                <a class="btn btn-dark "asp-controller="Genres" asp-action="PostByName"asp-route-id="@genre.Id"> See more</a>
            </div>
        </div>   
    }
</div>

Web/WonderlandBooks.Web/Views/Genres/PostByName.cshtml
@model WonderlandBooks.Web.ViewModels.Genres.GenrePostViewModel
@using WonderlandBooks.Common
@{
    this.ViewData["Title"] = "Topics";
}

@section Styles {
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="~/custom/post_comment.css" rel="stylesheet" />
}

<h1 class="display-4">@Model.Name</h1>
<hr />

@if (Model.Count == 0)
{
<div class="col-md-6 offset-md-3">
    <h3 >There are no discussions on this topic. </h3><a asp-controller="Posts" asp-action="Create">Be the first</a>
</div>
}
else
{
    @foreach (var post in Model.FormPost)
    {
        <div class="container bootdey">
            <div class="col-md-12 bootstrap snippets">


                <div class="panel">
                    <div class="panel-body">
                        <div class="media-block">

                            <div class="media-body">
                                <div class="mar-btm">
                                    <a asp-controller="Posts" asp-action="ById" asp-route-id="@post.Id">
                                        <h2 class=" text-semibold media-heading box-inline">@post.Title</h2>
                                    </a>
                                    <p class="text-muted text-sm"><i class="fa-solid fa-calendar-days"></i> @post.CreatedOn</p>
                                </div>
                                <p><strong>(@post.UserUserName)</strong></p>
                                <p>@Html.Raw(post.SanitizedContent)</p>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    }
    <nav>
        <ul class="pagination justify-content-center">
            <li class="page-item @if (!Model.HasPreviousPage)
        {<text>disabled</text>} ">
                <a class="page-link" asp-controller="Genres" asp-action="PostByName" asp-route-id="@Model.Id" asp-route-page="@Model.PreviousPageNumber">Previous</a>
            </li>
            @for (int i = Model.PageNumber - 3; i < Model.PageNumber; i++)
            {


                @if (i > 0)
                {
                    <li class="page-item"><a class="page-link" asp-controller="Genres" asp-action="PostByName" asp-route-id="@Model.Id" asp-route-page="@i">@i</a></li>

                }
            }
            <li class="page-item active" aria-current="page">
                <span class="page-link">
                    @Model.PageNumber
                    <span class="sr-only">(current)</span>
                </span>
            </li>
            @for (int i = Model.PageNumber + 1; i <= Model.PageNumber + 3; i++)
            {

                @if (i <= Model.PagesCount)
                {
                    <li class="page-item"><a class="page-link" asp-controller="Genres" asp-route-id="@Model.Id" asp-action="PostByName" asp-route-page="@i">@i</a></li>

                }
            }
            <li class="page-item @if (!Model.HasNextPage)
        { <text>disabled</text>}">
                <a class="page-link" asp-controller="Genres" asp-action="PostByName" asp-route-id="@Model.Id" asp-route-page="@Model.NextPageNumber">Next</a>

            </li>
        </ul>
    </nav>
}